# Generated by Django 2.2.16 on 2023-03-27 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 27, 16, 4, 20, 251601, tzinfo=utc), verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
