# Generated by Django 2.2.16 on 2023-03-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_image'),
        ('posts', '0009_follow'),
    ]

    operations = [
    ]
